name: Java CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        
  build-windows:
    runs-on: windows-latest
    if: false
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        
  build-mac:
    runs-on: macos-latest
    if: false
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

  check-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up Clang
        if: false
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo apt install llvm-21* clang-21* lld-21* lldb-21*
      - name: Clone winterfmt
        uses: actions/checkout@v5
        with:
          repository: WinterAlexander/winterfmt
          path: winterfmt
          ref: debug
      - name: Check format
        run: |
          clang-format --version
          source winterfmt/init.sh
          winterfmt check